name: grahamplaster
favicon: null
layout_spectrum: 0.5708379542920738
typography_spectrum: 0.23324485076591372
title: Graham Plaster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#818181'
    - '#fefefe'
    - '#3e3e3e'
    - '#b1b1b1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
